# Website
baseURL: "https://blog.crawfis.me"
languageCode: "en-us"
title: "Blog: Aaron Crawfis"

# Theme
theme: "hugo-clarity"

# Personalization
author: "Aaron Crawfis"
twitter: "AaronCrawfis"

mainSections:
  - post