name: App-Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: crawfis
          publish-profile: ${{ secrets.APPSERVICE_PROFILE }}
          package: ./html
          
