name: Deploy Homepage

on:
  push:
    branches: [ master ]
    paths:
      - "home/**"
      - ".github/workflows/home.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: crawfis
          publish-profile: ${{ secrets.APPSERVICE_PROFILE }}
          package: ./home
          
